### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by hareem-nisar** [tokjun/CurveMaker#14]
**What I did:** I place a bunch of fiducials (either manually or through sampling during tracking). They are all saved under one 'MarkerFiducial1'. Then I go to Curve Maker module. Select fiducial set as 'MarkerFiducial1' and for mode 'create new'. Then I press 'Generate' button and a curve/spline appears on the screen as expected. 
Now if I add more fiducial points and hit 'Generate' button again, the curve updates as expected. 

**What I expect:** I see that there is an 'Auto-generate' checkbox which should update the curve as soon as I place new fiducials. 

**What actually happened:** So I checked 'auto-generate'. then added a fiducial (and then more) but the curve did not update. If I unceck and recheck 'auto-generate' then the curve updates once. Adding more fiducials, the curve again did not update. 
If I add fiducials and hit 'generate' then the curve updates once (as expected)

**Summary:** The auto-update check-box is not working. and essentially acts like a 'generate' button. 

P.S. I am using Slicer nightly version 4.11.0 2019-07-23

**Comment by tokjun** [comment]
Hi @hareem-nisar ,

Thanks for the feedback. I hadn't tested the module on nightly builds recently, but after following your description, I could reproduce the issue on the latest build. My guess is that the module is not detecting the event when from the MarkupsFiducials node properly. I'll post once I fix that issue.

J

**Comment by tokjun** [comment]
The CurveMaker module observes "ModifiedEvent" to capture the change in the fiducial node (Line 412), but this doesn't seem to work for the latest Slicer. Instead, it should capture slicer.vtkMRMLMarkupsNode.PointModifiedEvent.

**Comment by tokjun** [comment]
I sent a pull request. The updated module will become available once the change is incorporated.

https://github.com/Slicer/ExtensionsIndex/pull/1657

**Comment by hareem-nisar** [comment]
Thank you so much

**Comment by tokjun** [comment]
The issue was resolved in revision 28488.
